# *** prod *** #
app_name = "gin-mongodb-pack"
version = "1.0.0-alpha" # 版本号
env = "prod"

port = 8000

# 日志配置
[log]
level = "info" # 日志等级，可选：debug, info, warn, error, dpanic, panic, fatal
root_dir = "./logs" # 日志根目录
filename = "app.log" # 日志文件名称
format = "console" # 写入格式，可选：console, json
show_line = true # 是否显示调用行
max_backups = 3 # 旧文件的最大个数
max_size = 200 # 日志文件最大大小（MB）
max_age = 28 # 旧文件的最大保留天数
compress = true # 是否压缩

# 数据库配置
[mongodb]
server = "localhost"